"""Helpers for referring to user content in logs without reproducing it."""

from __future__ import annotations

import hashlib
import logging
import re

__all__ = ["install_control_character_escaping", "install_http_url_redaction", "key_ref", "question_ref"]


def _ref(prefix: str, text: str) -> str:
    digest = hashlib.sha256(text.encode("utf-8")).hexdigest()[:12]
    return f"{prefix}[{digest} len={len(text)}]"


def question_ref(question: str | None) -> str:
    """A stable, non-reversible handle for a user's question.

    Logs used to carry the question itself, at INFO, on ordinary retrieval paths
    -- so anyone with log access read what every user asked, and truncating to
    the first 50 characters still reproduced the substance. The digest keeps the
    one property the logs actually needed: the same question produces the same
    handle, so a request can still be followed across lines and across services.

    Length is kept because it is useful for spotting empty or runaway inputs and
    reveals nothing on its own.
    """

    return _ref("q", str(question or ""))


def key_ref(key: str | None) -> str:
    """The same handle, for an identifier used as a partition or rate-limit key.

    A user id in a log line is not the disaster a question is, but it is still
    the one field that ties every other line to a person, and it is reproduced
    on paths that exist only to report a failure. The digest keeps what those
    lines are for -- telling whether the failures are one user or many -- and
    drops what they do not need.
    """

    return _ref("k", str(key or ""))


# C0 and C1 control characters, minus tab: a tab cannot start a new log line and
# legitimately appears in structured output. Newline and carriage return are the
# ones that matter -- they are what turns one attacker-controlled field into a
# second log record that looks like it came from this application.
_CONTROL_CHARACTERS = re.compile(r"[\x00-\x08\x0a-\x1f\x7f-\x9f]")

_INSTALLED = False


def _escaped(text: str) -> str:
    """Replace control characters with a visible escape, rather than dropping them.

    Dropping would silently rewrite the value; escaping keeps the evidence that
    something tried to inject one, which is the thing an operator reading the log
    afterwards actually wants to see.
    """

    return _CONTROL_CHARACTERS.sub(lambda m: f"\\x{ord(m.group()):02x}", text)


def install_control_character_escaping() -> None:
    """Make it impossible for a logged value to forge a log line.

    `pythonsecurity:S5145` fires wherever caller-controlled data reaches a
    logging call. In this application every such site logs an *identifier* --
    an execution id, a user key, a system name, a cache prefix -- not free text,
    so the risk is not disclosure but forgery: a path parameter carrying `%0A`
    decodes to a newline, and one log record becomes two.

    Fixing that at each call site means finding them all and keeping them found.
    This is the same defect in one place instead: a `LogRecord` factory that
    escapes control characters in the message and its arguments as the record is
    built, so it holds for every logger, every handler, and every call site that
    has not been written yet.

    Deliberately not touched: `exc_info`. A traceback is generated by the
    interpreter rather than by a caller, and mangling one would cost more than
    the forgery it prevents.

    Note for anyone comparing this against a scanner: Sonar's taint analysis does
    not see a record factory, so the S5145 findings stay open regardless. They
    are marked with a pointer here. The point of this function is the property,
    not the finding.
    """

    global _INSTALLED
    if _INSTALLED:
        return

    previous = logging.getLogRecordFactory()

    def factory(*args, **kwargs):
        record = previous(*args, **kwargs)
        if isinstance(record.msg, str):
            record.msg = _escaped(record.msg)
        if record.args:
            record.args = _escaped_record_args(record.args)
        return record

    logging.setLogRecordFactory(factory)
    _INSTALLED = True


# The HTTP clients the web search reaches the network through. Their records
# are scrubbed; the application's own are covered by `question_ref` and the AST
# guard over its logger calls, which cannot see inside a third-party library.
_HTTP_CLIENT_LOGGERS = ("httpx", "httpcore", "ddgs", "primp")

# The query string of a URL, up to the first character that ends a URL in
# prose or in a repr. Negated classes, no nested quantifiers: linear.
_URL_QUERY = re.compile(r"(https?://[^\s'\"()<>?]+)\?[^\s'\"()<>]*")

_URL_REDACTION_INSTALLED = False


def _without_url_queries(text: str) -> str:
    return _URL_QUERY.sub(r"\1?<query redacted>", text)


def install_http_url_redaction() -> None:
    """Keep outgoing request query strings out of HTTP client libraries' log lines.

    Web search sends the user's question as a URL parameter, and two libraries
    log that URL themselves, neither through code this repository can change:

    - httpx logs every request at INFO, `HTTP Request: GET <url> "HTTP/1.1 200 OK"`
      -- the question, on every Bing or SearXNG search, successful or not;
    - ddgs logs each failing engine at INFO as the exception's repr, and primp's
      error text is `error sending request for url (<url>)` -- measured, seven
      lines carrying the question for one DuckDuckGo search that failed.

    Both are invisible at startup, where the root logger sits at WARNING, and
    appear the moment an administrator sets INFO from the console (which "reset
    log levels" also does), into the buffer every administrator can read.

    A LogRecord factory rather than a level or a logger filter: the console's
    reset returns every logger to inheriting the root, which undoes a pinned
    level, and a filter on `ddgs` never sees a record logged on `ddgs.ddgs`,
    because logger filters do not apply to records propagated from children.
    The factory runs for every record at creation, whatever its logger's name.
    Idempotent, and it chains to whatever factory was installed before it.
    """

    global _URL_REDACTION_INSTALLED
    if _URL_REDACTION_INSTALLED:
        return

    previous = logging.getLogRecordFactory()

    def factory(*args, **kwargs):
        record = previous(*args, **kwargs)
        if record.name.split(".", 1)[0] in _HTTP_CLIENT_LOGGERS:
            try:
                message = record.getMessage()
            except (TypeError, ValueError):  # malformed args: leave the record as it came
                return record
            record.msg, record.args = _without_url_queries(message), None
        return record

    logging.setLogRecordFactory(factory)
    _URL_REDACTION_INSTALLED = True


def _escaped_record_args(args: dict | tuple) -> dict | tuple:
    """Escape every string value in a LogRecord's `args`, dict or positional."""
    if isinstance(args, dict):
        return {k: _escaped(v) if isinstance(v, str) else v for k, v in args.items()}
    return tuple(_escaped(a) if isinstance(a, str) else a for a in args)
