"""
简化的手动截图指南生成器
"""
import webbrowser
import time

print("=" * 60)
print("  QueryMind 截图助手")
print("=" * 60)
print()
print("📋 需要截取的页面：")
print()
print("1. 登录页面 (login.png) - ✓ 已完成")
print("2. 注册页面 (register.png) - 待截取")
print("3. 聊天界面 (chat.png) - 待截取")
print("4. 文档管理 (documents.png) - 待截取")
print("5. 知识图谱 (knowledge-graph.png) - 待截取")
print("6. 代理追踪 (agent-tracking.png) - 待截取")
print("7. 管理控制台 (admin-console.png) - 待截取")
print("8. 性能分析 (analytics.png) - 待截取")
print()
print("=" * 60)
print()

# 打开浏览器
print("🚀 正在打开应用...")
webbrowser.open("http://localhost:5173")
time.sleep(2)

print()
print("📝 截图步骤：")
print()
print("1. 在登录页面点击'注册'按钮")
print("   - 使用 Win + Shift + S 截图")
print("   - 保存为: docs/images/screenshots/register.png")
print()
print("2. 注册/登录账号")
print("   - 用户名: demo")
print("   - 密码: demo123")
print()
print("3. 进入聊天页面")
print("   - 输入一个问题并获得回答")
print("   - 截图保存为: chat.png")
print()
print("4. 依次访问并截图其他页面：")
print("   - /documents → documents.png")
print("   - /knowledge-graph → knowledge-graph.png")
print("   - /agent-tracking → agent-tracking.png")
print("   - /admin → admin-console.png")
print("   - /analytics → analytics.png")
print()
print("5. 完成后运行：")
print("   git add docs/images/screenshots/")
print("   git commit -m \"docs: add complete real application screenshots\"")
print("   git push origin main")
print()
print("=" * 60)
print()
input("按 Enter 键继续...")
